### ISSUE TITLE
Refined Storage external Storage

### ISSUE THREAD

**Issue by ferrium42** [Gogo08190/Chroma-Technology-2#8]
i´ve missing the external Storage bus . Don´t you wan´t we use refined Storage ? then remove it 
is there a bug or something, how can i enable it . i need to conect the drawer controller or it is useless.

**Comment by Gogo08190** [comment]
It's intentional use applied.

**Comment by darkphan** [comment]
Why even have refined storage in the pack, if its going to be be hampered like this? Why take people down an apparent dead end.

**Comment by VictorLeroux** [comment]
Because we wanted to do a kind of progression system, where refined is used temporarily. In fact some recipes for applied requires refined storage. What I see is that people use refined because it's easier but you will not be able to autocraft creative stuff. So I guess it's not a dead end like you said because applied is way more powerful and less laggy.

**Comment by Victor-Noli** [comment]
> 
> 
> Why even have refined storage in the pack, if its going to be be hampered like this? Why take people down an apparent dead end.

Because we wanted to do a kind of progression system, where refined is used temporarily. In fact some recipes for applied requires refined storage. What I see is that people use refined because it's easier but you will not be able to autocraft creative stuff. So I guess it's not a dead end like you said because applied is way more powerful and less laggy. But I guess that for you applied is complicated to use.
